version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"  # Mapea el puerto 3000 del host al puerto 3000 del contenedor
    environment:
      - PORT=3000
      - MONGO_URI_BASE=${MONGO_URI_BASE}
      - MONGO_DB_NAME=${MONGO_DB_NAME}
    env_file:
      - .env # Carga las variables de entorno desde el archivo .env
    volumes:
      - .:/app  # Mapea el código fuente local en el contenedor para facilitar el desarrollo
      - /app/node_modules # Usa una carpeta separada para node_modules en el contenedor
